### ISSUE TITLE
Selection box is drawn from point below timeline base on the Inception file

### ISSUE THREAD

**Issue by FelipeDefensor** [FelipeDefensor/TiLiA#4]

**Comment by FelipeDefensor** [comment]
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1948, in __call__
  File "tilia\ui\timelines\hierarchy\toolbar.py", line 23, in <lambda>
  File "tilia\events.py", line 151, in post
  File "tilia\ui\timelines\hierarchy\timeline.py", line 325, in on_merge_button
  File "tilia\timelines\hierarchy\timeline.py", line 70, in merge
  File "tilia\timelines\hierarchy\timeline.py", line 466, in merge
  File "tilia\timelines\hierarchy\timeline.py", line 500, in delete_component
  File "tilia\timelines\common.py", line 296, in request_delete_ui_for_component
  File "tilia\ui\timelines\timeline.py", line 509, in delete_element
  File "tilia\ui\timelines\timeline.py", line 843, in delete_element
  File "tilia\ui\timelines\timeline.py", line 728, in _remove_from_elements_set
KeyError: GUI for Hierarchy(2297757982032)
